### ISSUE TITLE
MustGetProcAddress

### ISSUE THREAD

**Issue by TongxiJi** [lxn/win#32]
environment:window xp 32bit , run on virtual box.

<img width="633" alt="qq20170822-173647 2x" src="https://user-images.githubusercontent.com/10556096/29559079-abc7930a-8760-11e7-9706-f999367bc8d1.png">

**Comment by lxn** [comment]
Sorry, XP is no longer supported.

**Comment by pravic** [comment]
@lxn was it supported? May be it is worth to have the winxp support in a separate branch?

**Comment by lxn** [comment]
Ok, just pushed an untested commit, please try if it fixes things.

This doesn't mean I intend to fix XP (or Vista or any other version not supported by MS) issues in the future. If anyone really needs support for those old versions, they will have to send a PR.

**Comment by pravic** [comment]
> MustGetProcAddress

You can add `MayGetProcAddress` for optional functions :) /joke

**Comment by TongxiJi** [comment]
Now the different  error .
<img width="621" alt="qq20170824-092650 2x" src="https://user-images.githubusercontent.com/10556096/29645189-6daf0c5c-88ae-11e7-8e39-eb37e5aa134b.png">

**Comment by lxn** [comment]
As you are probably on a 32 bit XP, I assume you try to load some 64 bit dll, which of course does not work.

**Comment by TongxiJi** [comment]
LOL,it works now.
