### ISSUE TITLE
Panic in last round of commits

### ISSUE THREAD

**Issue by dwall80** [lxn/win#39]
I'm running Win10 pro, all up to date

I'm using another package: https://github.com/sciter-sdk/go-sciter which has this as a dependency, I'm sorry I didn't capture the panic but it was pointing at this line here and failing during init:

https://github.com/lxn/win/blob/master/comctl32.go#L252

which I guess was not getting the address it wanted.

I checked out #1e0d6a9229bfb5986ba8b54e2ffc827233faa3e4 and the issue was resolved

Apologies this is not more thorough, if its not obvious shout back and Ill try recreate and grab any extra info you need

**Comment by lxn** [comment]
Please try if it works with latest changes.

**Comment by lkarlslund** [comment]
Yes, it does @lxn

**Comment by lxn** [comment]
Thanks
